/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface GrantFundingInterface extends ethers.utils.Interface {
  functions: {
    "claimGrant()": FunctionFragment;
    "createNewGrant(uint256,uint256,address)": FunctionFragment;
    "removeGrant(address)": FunctionFragment;
    "showGrant(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimGrant",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createNewGrant",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "removeGrant", values: [string]): string;
  encodeFunctionData(functionFragment: "showGrant", values: [string]): string;

  decodeFunctionResult(functionFragment: "claimGrant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNewGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "showGrant", data: BytesLike): Result;

  events: {
    "GrantClaimed(address,uint256,uint256)": EventFragment;
    "GrantFunded(uint256,address,uint256)": EventFragment;
    "GrantRemoved(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GrantClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantRemoved"): EventFragment;
}

export class GrantFunding extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GrantFundingInterface;

  functions: {
    claimGrant(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "claimGrant()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createNewGrant(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createNewGrant(uint256,uint256,address)"(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeGrant(
      _receipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "removeGrant(address)"(
      _receipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    showGrant(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, boolean] & {
          amount: BigNumber;
          unlockTime: BigNumber;
          fundWithdrawn: boolean;
        }
      ]
    >;

    "showGrant(address)"(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, boolean] & {
          amount: BigNumber;
          unlockTime: BigNumber;
          fundWithdrawn: boolean;
        }
      ]
    >;
  };

  claimGrant(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "claimGrant()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createNewGrant(
    _tokenAmount: BigNumberish,
    _unlockTime: BigNumberish,
    _receipent: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createNewGrant(uint256,uint256,address)"(
    _tokenAmount: BigNumberish,
    _unlockTime: BigNumberish,
    _receipent: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeGrant(
    _receipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "removeGrant(address)"(
    _receipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  showGrant(
    receiver: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      amount: BigNumber;
      unlockTime: BigNumber;
      fundWithdrawn: boolean;
    }
  >;

  "showGrant(address)"(
    receiver: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      amount: BigNumber;
      unlockTime: BigNumber;
      fundWithdrawn: boolean;
    }
  >;

  callStatic: {
    claimGrant(overrides?: CallOverrides): Promise<void>;

    "claimGrant()"(overrides?: CallOverrides): Promise<void>;

    createNewGrant(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "createNewGrant(uint256,uint256,address)"(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeGrant(_receipient: string, overrides?: CallOverrides): Promise<void>;

    "removeGrant(address)"(
      _receipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    showGrant(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        unlockTime: BigNumber;
        fundWithdrawn: boolean;
      }
    >;

    "showGrant(address)"(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        unlockTime: BigNumber;
        fundWithdrawn: boolean;
      }
    >;
  };

  filters: {
    GrantClaimed(
      receipent: string | null,
      amount: null,
      timeClaimed: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { receipent: string; amount: BigNumber; timeClaimed: BigNumber }
    >;

    GrantFunded(
      amount: null,
      receipent: string | null,
      timeLock: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { amount: BigNumber; receipent: string; timeLock: BigNumber }
    >;

    GrantRemoved(
      receipent: string | null,
      amount: null
    ): TypedEventFilter<
      [string, BigNumber],
      { receipent: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    claimGrant(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "claimGrant()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createNewGrant(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createNewGrant(uint256,uint256,address)"(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeGrant(
      _receipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "removeGrant(address)"(
      _receipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    showGrant(receiver: string, overrides?: CallOverrides): Promise<BigNumber>;

    "showGrant(address)"(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimGrant(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "claimGrant()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createNewGrant(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createNewGrant(uint256,uint256,address)"(
      _tokenAmount: BigNumberish,
      _unlockTime: BigNumberish,
      _receipent: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeGrant(
      _receipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "removeGrant(address)"(
      _receipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    showGrant(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "showGrant(address)"(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
