/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Grant {
  export type GrantStructStruct = {
    token: PromiseOrValue<string>;
    unlockTime: PromiseOrValue<BigNumberish>;
    claimedOrRevoked: PromiseOrValue<boolean>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type GrantStructStructOutput = [
    string,
    BigNumber,
    boolean,
    BigNumber
  ] & {
    token: string;
    unlockTime: BigNumber;
    claimedOrRevoked: boolean;
    amount: BigNumber;
  };
}

export interface GrantInterface extends utils.Interface {
  functions: {
    "checkGrantAmount()": FunctionFragment;
    "checkGrantClaimedOrRevoked()": FunctionFragment;
    "checkGrantUnlockTime()": FunctionFragment;
    "claim()": FunctionFragment;
    "deposit(address,uint256,address,uint256)": FunctionFragment;
    "grants(address)": FunctionFragment;
    "revoke(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "checkGrantAmount"
      | "checkGrantClaimedOrRevoked"
      | "checkGrantUnlockTime"
      | "claim"
      | "deposit"
      | "grants"
      | "revoke"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkGrantAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkGrantClaimedOrRevoked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkGrantUnlockTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkGrantAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkGrantClaimedOrRevoked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkGrantUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;

  events: {
    "GrantClaimed(tuple)": EventFragment;
    "GrantDeposited(address,address,uint256,uint256)": EventFragment;
    "GrantRevoked(tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GrantClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantRevoked"): EventFragment;
}

export interface GrantClaimedEventObject {
  grant: Grant.GrantStructStructOutput;
}
export type GrantClaimedEvent = TypedEvent<
  [Grant.GrantStructStructOutput],
  GrantClaimedEventObject
>;

export type GrantClaimedEventFilter = TypedEventFilter<GrantClaimedEvent>;

export interface GrantDepositedEventObject {
  token: string;
  recipient: string;
  amount: BigNumber;
  unlockTime: BigNumber;
}
export type GrantDepositedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  GrantDepositedEventObject
>;

export type GrantDepositedEventFilter = TypedEventFilter<GrantDepositedEvent>;

export interface GrantRevokedEventObject {
  grant: Grant.GrantStructStructOutput;
}
export type GrantRevokedEvent = TypedEvent<
  [Grant.GrantStructStructOutput],
  GrantRevokedEventObject
>;

export type GrantRevokedEventFilter = TypedEventFilter<GrantRevokedEvent>;

export interface Grant extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GrantInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkGrantAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    checkGrantClaimedOrRevoked(overrides?: CallOverrides): Promise<[boolean]>;

    checkGrantUnlockTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deposit(
      token: PromiseOrValue<string>,
      unlockTime: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    grants(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, boolean, BigNumber] & {
        token: string;
        unlockTime: BigNumber;
        claimedOrRevoked: boolean;
        amount: BigNumber;
      }
    >;

    revoke(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  checkGrantAmount(overrides?: CallOverrides): Promise<BigNumber>;

  checkGrantClaimedOrRevoked(overrides?: CallOverrides): Promise<boolean>;

  checkGrantUnlockTime(overrides?: CallOverrides): Promise<BigNumber>;

  claim(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deposit(
    token: PromiseOrValue<string>,
    unlockTime: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  grants(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, boolean, BigNumber] & {
      token: string;
      unlockTime: BigNumber;
      claimedOrRevoked: boolean;
      amount: BigNumber;
    }
  >;

  revoke(
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkGrantAmount(overrides?: CallOverrides): Promise<BigNumber>;

    checkGrantClaimedOrRevoked(overrides?: CallOverrides): Promise<boolean>;

    checkGrantUnlockTime(overrides?: CallOverrides): Promise<BigNumber>;

    claim(overrides?: CallOverrides): Promise<void>;

    deposit(
      token: PromiseOrValue<string>,
      unlockTime: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    grants(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, boolean, BigNumber] & {
        token: string;
        unlockTime: BigNumber;
        claimedOrRevoked: boolean;
        amount: BigNumber;
      }
    >;

    revoke(
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "GrantClaimed(tuple)"(grant?: null): GrantClaimedEventFilter;
    GrantClaimed(grant?: null): GrantClaimedEventFilter;

    "GrantDeposited(address,address,uint256,uint256)"(
      token?: null,
      recipient?: null,
      amount?: null,
      unlockTime?: null
    ): GrantDepositedEventFilter;
    GrantDeposited(
      token?: null,
      recipient?: null,
      amount?: null,
      unlockTime?: null
    ): GrantDepositedEventFilter;

    "GrantRevoked(tuple)"(grant?: null): GrantRevokedEventFilter;
    GrantRevoked(grant?: null): GrantRevokedEventFilter;
  };

  estimateGas: {
    checkGrantAmount(overrides?: CallOverrides): Promise<BigNumber>;

    checkGrantClaimedOrRevoked(overrides?: CallOverrides): Promise<BigNumber>;

    checkGrantUnlockTime(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deposit(
      token: PromiseOrValue<string>,
      unlockTime: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    grants(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revoke(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkGrantAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkGrantClaimedOrRevoked(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkGrantUnlockTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      token: PromiseOrValue<string>,
      unlockTime: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    grants(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revoke(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
